config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "decisions/",
        include(
            ("decisions.urls", "decisions"),
            namespace="decisions",
        ),
    ),
    path("users/", include(("users.urls", "users"), namespace="users")),
    path("", include(("core.urls", "core"), namespace="core")),
]

core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
]

core/models.py
from django.db import models


class TimestampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        abstract = True

core/views.py
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin


def index(request):
    if request.user.is_authenticated:
        return redirect(reverse("decisions:index"))
    return redirect(reverse("users:login"))

    
class ProtectedView(LoginRequiredMixin):
    login_url = "/users/login/"

templates/core/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %} {% block styles %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik+Moonrocks&display=swap" rel="stylesheet">
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma-rtl.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    {% endblock %}
    <title>Option Paralysis</title>
  </head>
  <body>
    <nav
      class="navbar is-dark"
      role="navigation"
      aria-label="main navigation"
    >
      <div class="container">
        <div class="navbar-brand">
	  <p id="logo" class="navbar-item">Option Paralysis</p>
          {% if user.is_authenticated %}
          <a class="navbar-item" href="{% url 'decisions:index' %}"
            >Home</a
          >
	  <a class="navbar-item" href="{% url 'users:logout' %}"
	  >Logout<span class="is-hidden-mobile">, {{ user.email }}</span></a>
          {% else %}
          <a class="navbar-item" href="{% url 'users:login' %}">Login</a>
          <a class="navbar-item navbar-end" href="{% url 'users:register' %}"
            >Register</a
          >
          {% endif %}
        </div>
      </div>
    </nav>
    <div class="container px-4 py-1">{% block body %}{% endblock %}</div>
    <script src="{% static 'js/formToggle.js' %}"></script>
    {% block scripts %} {% endblock %}
  </body>
</html>