config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "decisions/",
        include(
            ("decisions.urls", "decisions"),
            namespace="decisions",
        ),
    ),
    path("users/", include(("users.urls", "users"), namespace="users")),
    path("", include(("core.urls", "core"), namespace="core")),
]

core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

decisions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.DecisionView.as_view(), name="index"),
    path("create/", views.NewDecisionView.as_view(), name="create"),
    path("<int:pk>/", views.DecisionDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.DecisionDeleteView.as_view(), name="delete"),
    path("<int:pk>/update/", views.DecisionUpdateView.as_view(), name="update"),
    path("options/create/", views.NewOptionView.as_view(), name="options_create"),
    path(
        "options/<int:pk>/update/",
        views.OptionUpdateView.as_view(),
        name="options_update",
    ),
    path(
        "options/<int:pk>/delete/",
        views.OptionDeleteView.as_view(),
        name="options_delete",
    ),
    path(
        "options/<int:pk>/choose/",
        views.OptionChooseView.as_view(),
        name="options_choose",
    ),
    path("pros/create/", views.NewProView.as_view(), name="pros_create"),
    path("cons/create/", views.NewConView.as_view(), name="cons_create"),
    path("pros/<int:pk>/delete/", views.ProDeleteView.as_view(), name="pros_delete"),
    path("cons/<int:pk>/delete/", views.ConDeleteView.as_view(), name="cons_delete"),
    path("pros/<int:pk>/update/", views.ProUpdateView.as_view(), name="pros_update"),
    path("cons/<int:pk>/update/", views.ConUpdateView.as_view(), name="cons_update"),
]

decisions/models.py
from django.db import models
from django.db.models import Sum
from django.urls import reverse
from django.conf import settings

from core.models import TimestampedModel


class Decision(TimestampedModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("decisions:detail", kwargs={"pk": self.pk})


class Option(TimestampedModel):
    decision = models.ForeignKey(
        Decision, related_name="options", on_delete=models.CASCADE
    )
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    is_chosen = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def choose(self):
        options = Option.objects.filter(decision=self.decision).exclude(pk=self.pk)
        options.update(is_chosen=False)
        self.is_chosen = True
        self.save()

    def get_score(self):
        pro_sum = self.pros.aggregate(Sum("weight"))["weight__sum"]
        con_sum = self.cons.aggregate(Sum("weight"))["weight__sum"]
        return (pro_sum or 0) - (con_sum or 0)


class Pro(TimestampedModel):
    option = models.ForeignKey(Option, related_name="pros", on_delete=models.CASCADE)
    description = models.TextField()
    weight = models.IntegerField(default=1)

    def __str__(self):
        return self.description


class Con(TimestampedModel):
    option = models.ForeignKey(Option, related_name="cons", on_delete=models.CASCADE)
    description = models.TextField()
    weight = models.IntegerField(default=1)

    def __str__(self):
        return self.description

decisions/forms.py
from tkinter.ttk import Style
from django import forms

from .models import Decision, Option, Pro, Con


class DecisionForm(forms.ModelForm):
    class Meta:
        model = Decision
        fields = ["title", "description"]
        writeonly_fields = ["user"]
        widgets = {
            "title": forms.TextInput(
                attrs={"class": "input is-primary", "placeholder": "Add a decision"}
            ),
            "description": forms.Textarea(
                attrs={
                    "class": "textarea is-primary",
                    "placeholder": "Add a description",
                }
            ),
        }


class OptionForm(forms.ModelForm):
    class Meta:
        model = Option
        fields = ["title", "description"]
        writeonly_fields = ["decision"]
        widgets = {
            "title": forms.TextInput(
                attrs={"class": "input is-primary", "placeholder": "Add an option..."}
            ),
            "description": forms.Textarea(
                attrs={
                    "class": "textarea is-primary",
                    "placeholder": "Add a description...",
                }
            ),
        }


class ProForm(forms.ModelForm):
    class Meta:
        model = Pro
        fields = ["description", "weight"]
        writeonly_fields = ["option"]
        widgets = {
            "description": forms.TextInput(
                attrs={"class": "input is-success", "placeholder": "Add a pro..."}
            ),
            "weight": forms.NumberInput(
                attrs={
                    "class": "input is-success",
                    "initial": "1",
                }
            ),
        }


class ConForm(forms.ModelForm):
    class Meta:
        model = Con
        fields = ["description", "weight"]
        writeonly_fields = ["option"]
        widgets = {
            "description": forms.TextInput(
                attrs={"class": "input is-danger", "placeholder": "Add a con..."}
            ),
            "weight": forms.NumberInput(
                attrs={
                    "class": "input is-danger",
                    "initial": "1",
                }
            ),
        }

decisions/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic, View
from django.http import HttpResponseRedirect, Http404

from .models import Decision, Option, Pro, Con
from .forms import DecisionForm, OptionForm, ProForm, ConForm
from core.views import ProtectedView
from core.utils import get_object_or_none


class DecisionView(ProtectedView, generic.ListView):
    model = Decision
    context_object_name = "decisions"
    template_name = "decisions/index.html"
    paginate_by = 10

    def get_queryset(self):
        user = self.request.user
        decisions = DecisionView.model.objects.filter(user=user)
        decision_status = self.request.GET.get("status")
        if decision_status == "open":
            decisions = decisions.exclude(options__is_chosen=True)
        elif decision_status == "closed":
            decisions = decisions.filter(options__is_chosen=True)
        return decisions.order_by("-created_at")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = DecisionForm()
        context["filters"] = ["all", "open", "closed"]
        return context


class DecisionDetailView(ProtectedView, generic.DetailView):
    model = Decision
    context_object_name = "decision"
    template_name = "decisions/detail.html"

    def get_object(self, queryset=None):
        decision = get_object_or_404(Decision, pk=self.kwargs["pk"])
        return decision

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["chosen_option"] = get_object_or_none(
            Option, decision=self.object, is_chosen=True
        )
        context["option_form"] = OptionForm()
        context["pro_form"] = ProForm()
        context["con_form"] = ConForm()
        return context


class NewDecisionView(ProtectedView, generic.CreateView):
    model = Decision
    fields = ["title", "description"]

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)


class NewOptionView(ProtectedView, generic.CreateView):
    model = Option
    fields = ["decision", "title", "description"]
    template_name = "decisions/index.html"

    def get_success_url(self):
        return self.object.decision.get_absolute_url()


class NewProView(ProtectedView, generic.CreateView):
    model = Pro
    fields = ["option", "description", "weight"]

    def get_success_url(self):
        return self.object.option.decision.get_absolute_url()


class NewConView(ProtectedView, generic.CreateView):
    model = Con
    fields = ["option", "description", "weight"]

    def get_success_url(self):
        return self.object.option.decision.get_absolute_url()


class DecisionDeleteView(ProtectedView, generic.DeleteView):
    model = Decision
    template_name = "decisions/delete.html"

    def get_success_url(self):
        return reverse("decisions:index")


class OptionDeleteView(ProtectedView, generic.DeleteView):
    model = Option
    template_name = "decisions/delete.html"

    def get_success_url(self):
        return self.object.decision.get_absolute_url()


class ProDeleteView(ProtectedView, generic.DeleteView):
    model = Pro
    template_name = "decisions/delete.html"

    def get_success_url(self):
        return self.object.option.decision.get_absolute_url()


class ConDeleteView(ProtectedView, generic.DeleteView):
    model = Con
    template_name = "decisions/delete.html"

    def get_success_url(self):
        return self.object.option.decision.get_absolute_url()


class DecisionUpdateView(ProtectedView, generic.UpdateView):
    model = Decision
    fields = ["title", "description"]
    template_name = "decisions/update.html"

    def get_success_url(self):
        return self.object.get_absolute_url()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["action"] = reverse("decisions:update", kwargs={"pk": self.object.pk})
        return context


class OptionUpdateView(ProtectedView, generic.UpdateView):
    model = Option
    fields = ["title", "description"]
    template_name = "decisions/update.html"

    def get_success_url(self):
        return self.object.decision.get_absolute_url()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["action"] = reverse(
            "decisions:options_update", kwargs={"pk": self.object.pk}
        )
        return context


class ProUpdateView(ProtectedView, generic.UpdateView):
    model = Pro
    fields = ["description", "weight"]
    template_name = "decisions/update.html"

    def get_success_url(self):
        return self.object.option.decision.get_absolute_url()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["action"] = reverse(
            "decisions:pros_update", kwargs={"pk": self.object.pk}
        )
        return context


class ConUpdateView(ProtectedView, generic.UpdateView):
    model = Con
    fields = ["description", "weight"]
    template_name = "decisions/update.html"

    def get_success_url(self):
        return self.object.option.decision.get_absolute_url()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["action"] = reverse(
            "decisions:cons_update", kwargs={"pk": self.object.pk}
        )
        return context


class OptionChooseView(ProtectedView, View):
    def post(self, request, pk):
        data = request.POST
        try:
            option = Option.objects.get(pk=pk, decision__user=request.user)
        except Option.DoesNotExist:
            raise Http404
        if data["is_chosen"] == "true":
            option.choose()
        elif data["is_chosen"] == "false":
            option.is_chosen = False
            option.save()
        return HttpResponseRedirect(option.decision.get_absolute_url())

templates/decisions/delete.html
{% extends "core/layout.html" %} {% block body %}
<div class="m-2 p-2">
  <form method="post">
    {% csrf_token %}
    <p class="mb-2">Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <button class="button" type="button" onclick="window.history.back()">Cancel</button>
    <button type="submit" class="button is-danger">Delete</button>
  </form>
</div>
{% endblock %}

templates/decisions/detail.html
{% extends 'core/layout.html' %} {% block body %}

<!-- Decision -->
<div id="decision-info">
  <h1 class="is-size-2">{{ decision.title }}</h1>
  <p>{{ decision.description }}</p>
  {% if chosen_option %}
  <p class="is-size-6">
    <strong>Chosen option:</strong> {{ chosen_option.title }}
  </p>
  {% endif %}
</div>
<div class="my-3">
  <a class="button is-info" href="{% url 'decisions:update' decision.id %}"
    >Edit</a
  >
  <a class="button is-danger" href="{% url 'decisions:delete' decision.pk %}"
    >Delete</a
  >
  <button
    class="button is-primary toggle"
    data-target="option-form"
    data-content="option-list"
  >
    Add Option
  </button>
</div>

<!-- New Option Form -->
<form
  id="option-form"
  class="is-hidden"
  method="post"
  action="{% url 'decisions:options_create' %}"
>
  <input type="hidden" name="decision" value="{{ decision.pk }}" />
  {% csrf_token %} {{ option_form }}
  <button type="submit" class="button is-primary mt-3">Submit</button>
</form>

<!-- Options -->
<ul id="option-list">
  {% for option in decision.options.all %}
  <li class="card p-5 my-5">
    <div class="mb-5 has-text-centered">
      <h2 class="is-size-3">
        {{ option.title }}{% if option.is_chosen %} ✔️ {% endif %}
      </h2>
      <p class="is-size-5 mb-3">
        {% with score=option.get_score %} {{ score }} point{{ score|pluralize }}
        {% endwith %}
      </p>
      <form
        class="mb-3"
        action="{% url 'decisions:options_choose' option.pk %}"
        method="post"
      >
        {% csrf_token %} {% if option.is_chosen %}
        <input type="hidden" name="is_chosen" value="false" />
        <button type="submit" class="button is-danger">Unchoose</button>

        {% else %}
        <input type="hidden" name="is_chosen" value="true" />
        <button type="submit" class="button is-primary">Choose</button>
        {% endif %}
      </form>
      <a
        class="button is-info is-small is-rounded"
        href="{% url 'decisions:options_update' option.pk %}"
      >
        Edit
      </a>
      <a
        class="button is-danger is-small is-rounded"
        href="{% url 'decisions:options_delete' option.pk %}"
      >
        Delete
      </a>
    </div>

    <!-- Argyments -->
    <div class="columns">
      <!-- Pros -->
      <div class="column is-half">
        <h3 class="is-size-4">Pros</h3>
        <ul>
          {% for pro in option.pros.all %}
          <li class="is-flex is-justify-content-space-between mb-2">
            <span>
              {{ pro.description }}
              <span class="tag is-success">{{ pro.weight }}</span>
            </span>
            <span>
              <a
                class="button is-small is-info is-rounded"
                href="{% url 'decisions:pros_update' pro.pk %}"
                >Edit</a
              >
              <a
                class="button is-danger is-small is-rounded"
                href="{% url 'decisions:pros_delete' pro.pk %}"
                >Delete</a
              >
            </span>
          </li>
          {% endfor %}
        </ul>
        <a class="toggle button is-success" data-target="pro-{{ option.pk }}"
          >Add Pro</a
        >
        <form
          id="pro-{{ option.pk }}"
          class="is-hidden"
          method="post"
          action="{% url 'decisions:pros_create' %}"
        >
          <input type="hidden" name="option" value="{{ option.pk }}" />
          {% csrf_token %} {{ pro_form }}
          <button type="submit" class="button is-primary mt-3">Add</button>
        </form>
      </div>

      <!--- Cons -->
      <div class="column is-half">
        <h3 class="is-size-4">Cons</h3>
        <ul>
          {% for con in option.cons.all %}
          <li class="is-flex is-justify-content-space-between mb-2">
            <span>
              {{ con.description }}
              <span class="tag is-danger">{{ con.weight }}</span>
            </span>
            <span>
              <a
                class="button is-small is-info is-rounded"
                href="{% url 'decisions:cons_update' con.pk %}"
                >Edit</a
              >
              <a
                class="button is-danger is-small is-rounded"
                href="{% url 'decisions:cons_delete' con.pk %}"
              >
                Delete
              </a>
            </span>
          </li>
          {% endfor %}
        </ul>
        <a class="toggle button is-warning" data-target="con-{{ option.pk }}"
          >Add Con</a
        >
        <form
          id="con-{{ option.pk }}"
          class="is-hidden"
          method="post"
          action="{% url 'decisions:cons_create' %}"
        >
          <input type="hidden" name="option" value="{{ option.pk }}" />
          {% csrf_token %} {{ con_form }}
          <button type="submit" class="button is-primary mt-3">Add</button>
        </form>
      </div>
    </div>
  </li>
  {% empty %}
  <li>Add an option to get started.</li>
  {% endfor %}
</ul>

{% endblock %}

templates/decisions/index.html
{% extends 'core/layout.html' %} {% block body %}

<h1 class="is-size-2">Decisions</h1>

<!-- Filters -->
<div>
  <a
    href="{% url 'decisions:index' %}"
    class="button is-small {% if not request.GET.status %}is-active is-outlined{% else %}is-white{% endif %}"
    >All</a
  >
  <a
    href="{% url 'decisions:index' %}?status=open"
    class="button is-small {% if request.GET.status == 'open' %}is-active is-outlined{% else %}is-white{% endif %}"
    >Open</a
  >
  <a
    href="{% url 'decisions:index' %}?status=closed"
    class="button is-small {% if request.GET.status == 'closed' %}is-active is-outlined{% else %}is-white{% endif %}"
    >Closed</a
  >
</div>

<button
  class="button is-primary my-3 toggle"
  data-target="decision-form"
  data-content="decision-list"
>
  New Decision
</button>
<div id="decision-form" class="is-hidden">
  <form method="POST" action="{% url 'decisions:create' %}">
    {% csrf_token %} {{ form }}
    <button type="submit" class="button is-primary mt-3">Submit</button>
  </form>
</div>

<div id="decision-list">
  <ul>
    {% for decision in decisions %}
    <li>
      <a class="is-size-4" href="{% url 'decisions:detail' decision.pk %}">
        {{ decision.title }}
      </a>
      <div class="float-right">
        <a
          class="button is-info is-small is-rounded"
          href="{% url 'decisions:update' decision.pk %}"
        >
          Edit
        </a>
        <a
          class="button is-danger is-small is-rounded"
          href="{% url 'decisions:delete' decision.pk %}"
          >Delete
        </a>
      </div>
    </li>
    {% empty %}
    <li>No decisions found.</li>
    {% endfor %}
  </ul>

  <div class="pagination mt-3">
    <span class="step-links">
      {% if page_obj.has_previous %}
      <a class="button" href="?page=1">First</a>
      <a class="button" href="?page={{ page_obj.previous_page_number }}"
        >Previous</a
      >
      {% endif %}

      <div class="current my-2">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
      </div>

      {% if page_obj.has_next %}
      <a class="button" href="?page={{ page_obj.next_page_number }}">Next</a>
      <a class="button" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}
    </span>
  </div>
</div>

{% endblock %}

templates/decisions/update.html
{% extends 'core/layout.html' %} {% block body %} {% load model_extras %}
<h1 class="is-size-2">Update {{ object|model_name }}</h1>
<form method="post" action="{{ action }}">
  {% csrf_token %} {% for field in form %}
  <label for="{{ field.id_for_label }}">{{ field.label }}</label>
  <input
    id="{{ field.id_for_label }}"
    name="{{ field.html_name }}"
    type="{% if field.html_name == 'weight' %}number{% else %}text{% endif %}"
    class="input is-primary mb-3"
    placeholder="{{ field.label }}"
    value="{{ field.value }}"
  />
  {% if field.errors %}
  <p>{{ field.help_text }}</p>
  {% endif %} {% endfor %}
  <button type="button" class="button" onclick="window.history.back()">
    Cancel
  </button>
  <button type="submit" class="button is-primary">Update</button>
</form>

<script>
  const inputs = Array.from(document.querySelectorAll("input")).filter(
    (input) => input.type !== "hidden"
  );
  const input = inputs[0];
  input.focus();

  // Move cursor to end of input
  const value = input.value;
  input.value = "";
  input.value = value;
</script>
{% endblock %}